// <auto-generated />
using System;
using ClinicManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicManagement.Domain.Entity.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AdminId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            CreatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 156, DateTimeKind.Utc).AddTicks(2335),
                            Email = "admin@gmail.com",
                            FullName = "System Administrator",
                            Id = 0,
                            IsActive = true,
                            PasswordHash = "$2a$11$ZNwXzHwf1rJUwxCZ27ygm.QkEItTRnOA.Rw3zuIOOMSp3tM.zhI.q",
                            Phone = "19001898",
                            UpdatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 156, DateTimeKind.Utc).AddTicks(2336)
                        });
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime?>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByDoctorId")
                        .HasColumnType("int");

                    b.Property<int?>("CancelledByAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int?>("ExamId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("AppointmentId");

                    b.HasIndex("ApprovedByDoctorId");

                    b.HasIndex("ExamId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_App_Patient");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("DoctorId", "AppointmentDate")
                        .HasDatabaseName("IX_App_Doctor_Date");

                    b.ToTable("Appointments", t =>
                        {
                            t.HasCheckConstraint("CK_App_Status", "Status in ('pending','approved','rejected','cancelled','completed')");
                        });
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("DepartmentId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            Code = "CARD",
                            CreatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 157, DateTimeKind.Utc).AddTicks(8917),
                            Description = "Khoa Tim mạch",
                            Id = 0,
                            IsActive = true,
                            Name = "Cardiology",
                            UpdatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 157, DateTimeKind.Utc).AddTicks(8918)
                        },
                        new
                        {
                            DepartmentId = 2,
                            Code = "DERM",
                            CreatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 157, DateTimeKind.Utc).AddTicks(8922),
                            Description = "Khoa Da liễu",
                            Id = 0,
                            IsActive = true,
                            Name = "Dermatology",
                            UpdatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 157, DateTimeKind.Utc).AddTicks(8923)
                        },
                        new
                        {
                            DepartmentId = 3,
                            Code = "NEUR",
                            CreatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 157, DateTimeKind.Utc).AddTicks(8924),
                            Description = "Khoa Thần kinh",
                            Id = 0,
                            IsActive = true,
                            Name = "Neurology",
                            UpdatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 157, DateTimeKind.Utc).AddTicks(8925)
                        },
                        new
                        {
                            DepartmentId = 4,
                            Code = "PED",
                            CreatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 157, DateTimeKind.Utc).AddTicks(8958),
                            Description = "Khoa Nhi",
                            Id = 0,
                            IsActive = true,
                            Name = "Pediatrics",
                            UpdatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 157, DateTimeKind.Utc).AddTicks(8958)
                        },
                        new
                        {
                            DepartmentId = 5,
                            Code = "ORTH",
                            CreatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 157, DateTimeKind.Utc).AddTicks(8960),
                            Description = "Khoa Chấn thương chỉnh hình",
                            Id = 0,
                            IsActive = true,
                            Name = "Orthopedics",
                            UpdatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 157, DateTimeKind.Utc).AddTicks(8960)
                        });
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Specialization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("DoctorId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.DoctorDepartment", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("DoctorId", "DepartmentId");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_DocDept_Department");

                    b.HasIndex("DoctorId")
                        .IsUnique()
                        .HasDatabaseName("UX_DoctorDepartments_Primary")
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("DoctorDepartments");
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.DoctorSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("CreatedByStaffId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxPatients")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("ScheduleId");

                    b.HasIndex("CreatedByStaffId");

                    b.HasIndex("DoctorId", "StartTime")
                        .HasDatabaseName("IX_Schedule_DoctorTime");

                    b.ToTable("DoctorSchedules", t =>
                        {
                            t.HasCheckConstraint("CK_Sched_Time", "EndTime > StartTime");
                        });
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Examination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ExaminationType")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("ExamId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("PatientId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 154, DateTimeKind.Utc).AddTicks(1824),
                            Id = 0,
                            IsActive = true,
                            Name = "Admin",
                            UpdatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 154, DateTimeKind.Utc).AddTicks(1826)
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 154, DateTimeKind.Utc).AddTicks(1830),
                            Id = 0,
                            IsActive = true,
                            Name = "Staff",
                            UpdatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 154, DateTimeKind.Utc).AddTicks(1830)
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 154, DateTimeKind.Utc).AddTicks(1832),
                            Id = 0,
                            IsActive = true,
                            Name = "Doctor",
                            UpdatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 154, DateTimeKind.Utc).AddTicks(1832)
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 154, DateTimeKind.Utc).AddTicks(1833),
                            Id = 0,
                            IsActive = true,
                            Name = "Patient",
                            UpdatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 154, DateTimeKind.Utc).AddTicks(1833)
                        },
                        new
                        {
                            RoleId = 5,
                            CreatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 154, DateTimeKind.Utc).AddTicks(1835),
                            Id = 0,
                            IsActive = true,
                            Name = "Staff_Doctor",
                            UpdatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 154, DateTimeKind.Utc).AddTicks(1835)
                        },
                        new
                        {
                            RoleId = 6,
                            CreatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 154, DateTimeKind.Utc).AddTicks(1836),
                            Id = 0,
                            IsActive = true,
                            Name = "Staff_Patient",
                            UpdatedAt = new DateTime(2025, 9, 18, 9, 59, 26, 154, DateTimeKind.Utc).AddTicks(1836)
                        });
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("StaffId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.Admin", b =>
                {
                    b.HasOne("ClinicManagement.Domain.Entity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.Appointment", b =>
                {
                    b.HasOne("ClinicManagement.Domain.Entity.Doctor", "ApprovedByDoctor")
                        .WithMany()
                        .HasForeignKey("ApprovedByDoctorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ClinicManagement.Domain.Entity.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ClinicManagement.Domain.Entity.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ClinicManagement.Domain.Entity.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManagement.Domain.Entity.DoctorSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ApprovedByDoctor");

                    b.Navigation("Doctor");

                    b.Navigation("Exam");

                    b.Navigation("Patient");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.Doctor", b =>
                {
                    b.HasOne("ClinicManagement.Domain.Entity.Role", "Role")
                        .WithMany("Doctors")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.DoctorDepartment", b =>
                {
                    b.HasOne("ClinicManagement.Domain.Entity.Department", "Department")
                        .WithMany("DoctorDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManagement.Domain.Entity.Doctor", "Doctor")
                        .WithMany("DoctorDepartments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.DoctorSchedule", b =>
                {
                    b.HasOne("ClinicManagement.Domain.Entity.Staff", "CreatedByStaff")
                        .WithMany()
                        .HasForeignKey("CreatedByStaffId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ClinicManagement.Domain.Entity.Doctor", "Doctor")
                        .WithMany("Schedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByStaff");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.Exam", b =>
                {
                    b.HasOne("ClinicManagement.Domain.Entity.Department", "Department")
                        .WithMany("Exams")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.Patient", b =>
                {
                    b.HasOne("ClinicManagement.Domain.Entity.Role", "Role")
                        .WithMany("Patients")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.Staff", b =>
                {
                    b.HasOne("ClinicManagement.Domain.Entity.Role", "Role")
                        .WithMany("Staffs")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.Department", b =>
                {
                    b.Navigation("DoctorDepartments");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorDepartments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClinicManagement.Domain.Entity.Role", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Patients");

                    b.Navigation("Staffs");
                });
#pragma warning restore 612, 618
        }
    }
}
